### ISSUE TITLE
Problem with select: no element

### ISSUE THREAD

**Issue by v-araya** [michaschwab/ssvg#11]
Hello!

I've been trying to include SSVG to my project but I'm having a weird problem with d3.select as I receive a "no element" error. I tried with other basic queries both in my code and in the console (e.g. d3.select('body')) and I have the same issue. This error disappears if I don't include SSVG. The way I included SSVG is by adding the following line after the d3 (d3.v5.min.js) declaration:

`<script src="https://intervis-projects.ccs.neu.edu/ssvg/ssvg-auto.js"></script>` 

I also tried to put it before and after the <body> tag. Additionally I tested it with both Chrome and Firefox but always with the same result. Any idea why this could be happening?

Cheers and thanks,
Vanessa

**Comment by michaschwab** [comment]
I guess this is the same as issue #9. Responding there.
