### ISSUE TITLE
Is there any way ssvg can be used with easypz?

### ISSUE THREAD

**Issue by robskrob** [michaschwab/ssvg#8]
Hi  -- I need to make an interactive map of a building site and my designer has provided me with a large / complex SVG. I like the interactivity that comes out of the box with [easypz](https://github.com/michaschwab/easypz), but I notice that the SVG with `easypz` hits the browser hard in terms of performance. I see that `ssvg` is mainly for `d3`. 

Is it possible to use `ssvg` with `easypz` so that I can leverage the interactivity and easy of use of `easypz` with the performance gains of `ssvg`?

**Comment by michaschwab** [comment]
Hey @robskrob! Thanks for your request. I'm happy to hear you're interested in using easypz and ssvg together! I don't think they have been used together before, so there are likely some practical issues to work out. In theory though they should be able to cooperate. I'll try to come up with an example for you in the next few days.

**Comment by robskrob** [comment]
@michaschwab thank you for looking into this!

**Comment by michaschwab** [comment]
I pushed some minor fixes in both EasyPZ and in SSVG to get them to play nice. Here's a demo: http://michailschwab.com/tiger/

I don't know if SSVG will actually be helpful in getting a very large static SVG to be rendered efficiently, as that isn't exactly what I built SSVG for. Please let me know how it goes! If it doesn't render smoothly, there might be some things we can do.
